Repository DeveloperAcademy-POSTECH/MC3-Team5-Mondee, pull requests merged in 2023-07, with the labels that each got.

#17 docs: PR 템플릿 업데이트
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🖊️ Docs

#22 [watchOS] design: 게임옵션뷰 추가 (#10)
  Mondee Watch App/View/GameOptionView.swift
  Mondee.xcodeproj/project.pbxproj
  Mondee.xcodeproj/xcuserdata/hyunjun.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: ✨ Feature, 🎨 UI/UX

#20 [watchOS] feat: 게임 전 설명 안내 (#4)
  Mondee Watch App/Assets.xcassets/Images/ImageWatch/ImageWatchBubble.imageset/Bubble.png
  Mondee Watch App/Assets.xcassets/Images/ImageWatch/ImageWatchBubble.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImageWatch/ImageWatchBubblePung.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImageWatch/ImageWatchBubblePung.imageset/Group 176.png
  Mondee Watch App/Assets.xcassets/Images/ImageWatch/ImageWatchBubbles.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImageWatch/ImageWatchBubbles.imageset/Group 173.png
  Mondee Watch App/View/BeforGame/BeforeGameCountView.swift
  Mondee Watch App/View/BeforGame/BeforeGameView.swift
  Mondee Watch App/View/GameView.swift
  Mondee.xcodeproj/project.pbxproj
Labels: ⌚️ watchOS, ✨ Feature, 👏 Improvement

#19 [watchOS] feat: 청소 게임 구현 (#5)
  Mondee Watch App/Assets.xcassets/Images/Heart-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/Heart-WatchOS.imageset/Heart-WatchOS.png
  Mondee Watch App/Assets.xcassets/Images/ImageWatch/ImageWatchBubblePung.imageset/Group 176.png
  Mondee Watch App/Assets.xcassets/Images/ImgBathTubBubble-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImgBathTubBubble-WatchOS.imageset/ImgBathTubBubble-WatchOS.png
  Mondee Watch App/Assets.xcassets/Images/ImgBathTubTower-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImgBathTubTower-WatchOS.imageset/ImgBathTubTower-WatchOS.png
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeBasic-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeBasic-WatchOS.imageset/ImgMondeeBasic-WatchOS.png
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeBlack-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeBlack-WatchOS.imageset/ImgMondeeBlack-WatchOS.png
  Mondee Watch App/Constants.swift
  Mondee Watch App/Extension/SessionExtend.swift
  Mondee Watch App/View/GameView.swift
  Mondee Watch App/View/Guide/BeforeGameCountView.swift
  Mondee Watch App/View/Guide/GuideView.swift
  Mondee Watch App/View/Play/GameOptionView.swift
  Mondee Watch App/View/Play/PlayView.swift
  Mondee Watch App/View/Preparation/ArrowAnimation.swift
  Mondee Watch App/View/Preparation/Mondee.swift
  Mondee Watch App/View/Preparation/PreparationView.swift
  Mondee Watch App/View/Result/ResultView.swift
  Mondee Watch App/ViewModel/GameStateManager.swift
  Mondee Watch App/ViewModel/MovingDetector.swift
  Mondee Watch App/ViewModel/WatchSampleViewModel.swift
  Mondee-Watch-App-Info.plist
  Mondee.xcodeproj/project.pbxproj
Labels: ⌚️ watchOS, ✨ Feature

#28 [watchOS] feat: 게임 성공/ 실패 뷰 (#11)
  Mondee Watch App/Assets.xcassets/ImgFail-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/ImgFail-WatchOS.imageset/Group 174.png
  Mondee Watch App/Assets.xcassets/ImgSuccess-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/ImgSuccess-WatchOS.imageset/Group 931.png
  Mondee Watch App/View/FailView.swift
  Mondee Watch App/View/SuccessView.swift
  Mondee.xcodeproj/project.pbxproj
Labels: ⌚️ watchOS, 🎨 UI/UX

#29 [watchOS] feat: 게임 시작 전 카운트 다운 원형 그래프 구현 (#23)
  Mondee Watch App/View/Guide/BeforeGameCountView.swift
  Mondee Watch App/View/Guide/GuideView.swift
  Mondee Watch App/View/Modifier/Modifier.swift
  Mondee.xcodeproj/project.pbxproj
Labels: ⌚️ watchOS, ✨ Feature

#32 [watchOS] feat: 게임 옵션 스크린 동작 (#24)
  Mondee Watch App/Constants.swift
  Mondee Watch App/View/GameView.swift
  Mondee Watch App/View/Play/GameOptionView.swift
  Mondee Watch App/View/Play/PlayView.swift
  Mondee Watch App/View/Result/FinalFailView.swift
  Mondee Watch App/View/Result/ResultView.swift
  Mondee Watch App/View/Result/SuccessView.swift
  Mondee Watch App/View/Result/retryFailView.swift
  Mondee Watch App/ViewModel/GameStateManager.swift
  Mondee Watch App/ViewModel/MovingDetector.swift
  Mondee.xcodeproj/project.pbxproj
Labels: ⌚️ watchOS, ✨ Feature

#38 [watchOS] feat: 청소 게임 UI assets 적용 (#33)
  Mondee Watch App/Assets.xcassets/Images/ImgHeart-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImgHeart-WatchOS.imageset/Heart-WatchOS.png
  Mondee Watch App/Assets.xcassets/Images/ImgHeartClear-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImgHeartClear-WatchOS.imageset/HeartClear-WatchOS.png
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeBasic-WatchOS.imageset/ImgMondeeBasic-WatchOS.png
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeBlack-WatchOS.imageset/ImgMondeeBlack-WatchOS.png
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeHappy-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeHappy-WatchOS.imageset/ImgMondeeHappy-WatchOS.png
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeHappySmile-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeHappySmile-WatchOS.imageset/ImgMondeeHappySmile-WatchOS.png
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeSad-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeSad-WatchOS.imageset/ImgMondeeSad-WatchOS.png
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeWhite-WatchOS.imageset/Contents.json
  Mondee Watch App/Assets.xcassets/Images/ImgMondeeWhite-WatchOS.imageset/ImgMondeeWhite-WatchOS.png
  Mondee Watch App/Constants.swift
  Mondee Watch App/View/Play/PlayView.swift
  Mondee.xcodeproj/project.pbxproj
Labels: ⌚️ watchOS, 🎨 UI/UX

#39 [watchOS] feat: 사용자 움직임 관련 동작 기능 추가 (#25)
  Mondee Watch App/Constants.swift
  Mondee Watch App/View/Play/HeartCountView.swift
  Mondee Watch App/View/Play/MondeeImageView.swift
  Mondee Watch App/View/Play/PlayView.swift
  Mondee Watch App/ViewModel/GameStateManager.swift
  Mondee.xcodeproj/project.pbxproj
Labels: ⌚️ watchOS, ✨ Feature

#40 [WatchOS] feat: 다른 날마다 게임상태를 초기화 기능 추가 (#26)
  Mondee Watch App/MondeeApp.swift
  Mondee Watch App/View/ContentView.swift
  Mondee Watch App/View/GameView.swift
  Mondee Watch App/View/Play/GameOptionView.swift
  Mondee Watch App/View/Play/PlayView.swift
  Mondee Watch App/View/Result/FinalFailView.swift
  Mondee Watch App/View/Result/SuccessView.swift
  Mondee Watch App/ViewModel/GameStateManager.swift
  Mondee.xcodeproj/project.pbxproj
Labels: ⌚️ watchOS, ✨ Feature

#42 [watchOS] fix: 카운트 다운 버그 수정 (#41)
  Mondee Watch App/View/Play/PlayView.swift
  Mondee Watch App/View/Play/WarningView.swift
  Mondee.xcodeproj/project.pbxproj
Labels: 🐞 Bugfix, ⌚️ watchOS

#59 [watchOS] feat: 애플워치 데이터 아이폰 전송 Sample 구현
  Mondee Watch App/Model/GameResultModel.swift
  Mondee Watch App/MondeeApp.swift
  Mondee Watch App/View/Result/FinalFailView.swift
  Mondee Watch App/View/Result/RetryFailView.swift
  Mondee Watch App/View/Result/SuccessView.swift
  Mondee Watch App/ViewModel/GameStateManager.swift
  Mondee Watch App/ViewModel/MovingDetector.swift
  Mondee.xcodeproj/project.pbxproj
  Mondee.xcodeproj/xcuserdata/hyunjun.xcuserdatad/xcschemes/xcschememanagement.plist
  Mondee/View/ReceiveDataSampleView.swift
Labels: ⌚️ watchOS, ✨ Feature

#60 [iOS] feat: Tab Navigation 구현 (#53)
  Mondee.xcodeproj/project.pbxproj
  Mondee.xcodeproj/xcuserdata/hyunjun.xcuserdatad/xcschemes/xcschememanagement.plist
  Mondee/Model/TabModel.swift
  Mondee/View/CleanRoomView/CleanRoomView.swift
  Mondee/View/ContentView.swift
  Mondee/View/CustomTabView.swift
  Mondee/View/RecordView/RecordView.swift
  Mondee/View/TabBar/CustomTabBar.swift
  Mondee/View/TodayView/TodayView.swift
Labels: 🍎 iOS, ✨ Feature

#62 [watchOS] design: 축하 세러모니 추가 및 세부 UI 개선 (#61)
  Mondee Watch App/View/Guide/GuideView.swift
  Mondee Watch App/View/Play/GameOptionView.swift
  Mondee Watch App/View/Play/PlayView.swift
  Mondee Watch App/View/Result/Confetti/ConfettiCannon.swift
  Mondee Watch App/View/Result/Confetti/ConfettiSwiftUI.swift
  Mondee Watch App/View/Result/Confetti/RoundedCross.swift
  Mondee Watch App/View/Result/Confetti/SlimRectangle.swift
  Mondee Watch App/View/Result/Confetti/Triangle.swift
  Mondee Watch App/View/Result/FinalFailView.swift
  Mondee Watch App/View/Result/SuccessView.swift
  Mondee.xcodeproj/project.pbxproj
  Mondee.xcodeproj/xcuserdata/hyunjun.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: ⌚️ watchOS, ✨ Feature

#67 [WatchOS] feat: 하트 감소때마다 하트 개수 데이터 전송 기능 구현
  Mondee Watch App/Model/GameResultModel.swift
  Mondee Watch App/View/Result/FinalFailView.swift
  Mondee Watch App/View/Result/SuccessView.swift
  Mondee Watch App/ViewModel/GameStateManager.swift
  Mondee.xcodeproj/project.pbxproj
  Mondee.xcodeproj/xcshareddata/xcschemes/Mondee Watch App.xcscheme
  Mondee.xcodeproj/xcshareddata/xcschemes/Mondee.xcscheme
  Mondee/View/ReceiveDataSampleView.swift
Labels: ⌚️ watchOS, ✨ Feature

#69 [iOS] feat: 청소 등급 기능 구현 (#46)
  Mondee.xcodeproj/project.pbxproj
  Mondee/Assets.xcassets/Colors/mondeeDarkGrey.colorset/Contents.json
  Mondee/Assets.xcassets/MondeeImg/Contents.json
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeLevel1-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeLevel1-IOS.imageset/ImgMondeeLevel1-IOS.png
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeLevel2-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeLevel2-IOS.imageset/ImgMondeeLevel2-IOS.png
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeLevel3-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeLevel3-IOS.imageset/ImgMondeeLevel3-IOS.png
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeLevel4-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeLevel4-IOS.imageset/ImgMondeeLevel4-IOS.png
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeLevel5-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeLevel5-IOS.imageset/ImgMondeeLevel5-IOS.png
  Mondee/Model/TodayModel.swift
  Mondee/View/DesignSystem/ColorSystem.swift
  Mondee/View/TodayView/MondeeBoxView.swift
  Mondee/View/TodayView/MondeeLevelView.swift
  Mondee/View/TodayView/TodayView.swift
  Mondee/ViewModel/TodayViewModel.swift
Labels: 🍎 iOS, ✨ Feature

#71 [iOS] feat: 캐릭터 터치 시 대사 변경 기능 (#48)
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeCaution-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeCaution-IOS.imageset/ImgMondeeCaution-IOS.png
  Mondee/Assets.xcassets/MondeeImg/ImgMondeePudding-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/MondeeImg/ImgMondeePudding-IOS.imageset/ImgMondeePudding-IOS.png
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeShadow-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeShadow-IOS.imageset/ImgMondeeShadowDark-IOS.png
  Mondee/Assets.xcassets/MondeeImg/ImgMondeeShadow-IOS.imageset/ImgMondeeShadowLight-IOS.png
  Mondee/Model/TodayModel.swift
  Mondee/View/TodayView/MondeeBoxView.swift
  Mondee/View/TodayView/MondeeLevelView.swift
  Mondee/ViewModel/TodayViewModel.swift
Labels: ✨ Feature

#76 [iOS] feat: 캘린더 뷰 대시보드 구현 (#55)
  Mondee.xcodeproj/project.pbxproj
  Mondee/Assets.xcassets/Image/Contents.json
  Mondee/Assets.xcassets/Image/ImgStatisticsMonth.imageset/Contents.json
  Mondee/Assets.xcassets/Image/ImgStatisticsMonth.imageset/ImgStatisticsMonth.png
  Mondee/Assets.xcassets/Image/ImgStatisticsRate.imageset/Contents.json
  Mondee/Assets.xcassets/Image/ImgStatisticsRate.imageset/ImgStatisticsRate.png
  Mondee/Assets.xcassets/Image/ImgStatisticsTotal.imageset/Contents.json
  Mondee/Assets.xcassets/Image/ImgStatisticsTotal.imageset/ImgStatisticsTotal.png
  Mondee/Assets.xcassets/Image/bubbles.imageset/Contents.json
  Mondee/Assets.xcassets/Image/bubbles.imageset/bubbles.png
  Mondee/MondeeApp.swift
  Mondee/View/RecordView/DateExtensions.swift
  Mondee/View/RecordView/DateViewModel.swift
  Mondee/View/RecordView/MonthStatistics.swift
  Mondee/View/RecordView/RecordCalendarArea.swift
  Mondee/View/RecordView/RecordCalendarView.swift
  Mondee/View/RecordView/RecordTitleArea.swift
  Mondee/View/RecordView/RecordView.swift
  Mondee/View/RecordView/TotalStatistics.swift
Labels: 🍎 iOS, ✨ Feature

#77 [iOS] feat: 멸균실 스크린 구현 (#56)
  Mondee.xcodeproj/project.pbxproj
  Mondee/Assets.xcassets/CollectedMondeeImg/Contents.json
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee001-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee001-IOS.imageset/ImgCollectedMondee001-IOS.png
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee002-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee002-IOS.imageset/ImgCollectedMondee002-IOS.png
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee003-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee003-IOS.imageset/ImgCollectedMondee003-IOS.png
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee004-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee004-IOS.imageset/ImgCollectedMondee004-IOS.png
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee005-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee005-IOS.imageset/ImgCollectedMondee005-IOS.png
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee006-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee006-IOS.imageset/ImgCollectedMondee006-IOS.png
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee007-IOS.imageset/Contents.json
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee007-IOS.imageset/ImgCollectedMondee007-IOS.png
  Mondee/Assets.xcassets/Colors/mondeeDarkBlue.colorset/Contents.json
  Mondee/Model/CleanRoomModel.swift
  Mondee/View/CleanRoomView/CleanRoomView.swift
  Mondee/View/CleanRoomView/CollectedMondeeDetailCardView.swift
  Mondee/View/CleanRoomView/CollectedMondeeGridView.swift
  Mondee/View/CleanRoomView/LatestCollectedMondeeView.swift
  Mondee/View/DesignSystem/ButtonSystem.swift
  Mondee/View/DesignSystem/ColorSystem.swift
  Mondee/View/TabBar/CustomTabBar.swift
  Mondee/ViewModel/CleanViewModel.swift
Labels: 🍎 iOS, ✨ Feature

#74 [iOS] 청소레벨 팝업 구현 (#46)
  Mondee.xcodeproj/project.pbxproj
  Mondee/Assets.xcassets/PopupImg/Contents.json
  Mondee/Assets.xcassets/PopupImg/ImgAfterSucessPopup-iOS.imageset/Contents.json
  Mondee/Assets.xcassets/PopupImg/ImgAfterSucessPopup-iOS.imageset/ImgAfterSuccessPopup.png
  Mondee/Model/TodayModel.swift
  Mondee/View/TodayView/AfterSuccessPopupView.swift
  Mondee/View/TodayView/LevelPopupView.swift
  Mondee/View/TodayView/MondeeLevelView.swift
  Mondee/View/TodayView/TodayView.swift
Labels: 🍎 iOS, ✨ Feature

#82 [watchOS] feat: 게임이 끝나는 모든 경우의 수에서 데이터 전송 기능 구현
  Mondee Watch App/Model/WatchDataModel.swift
  Mondee Watch App/Model/WatchSampleModel.swift
  Mondee Watch App/View/ContentView.swift
  Mondee Watch App/View/GameView.swift
  Mondee Watch App/View/Play/GameOptionView.swift
  Mondee Watch App/View/Play/HeartCountView.swift
  Mondee Watch App/View/Play/PlayView.swift
  Mondee Watch App/View/Result/FinalFailView.swift
  Mondee Watch App/View/Result/RetryFailView.swift
  Mondee Watch App/View/Result/SuccessView.swift
  Mondee Watch App/ViewModel/DeviceCommunicator.swift
  Mondee Watch App/ViewModel/GameStateManager.swift
  Mondee.xcodeproj/project.pbxproj
  Mondee/Model/PhoneDataModel.swift
  Mondee/Model/SampleModel.swift
  Mondee/Model/UserDataModel.swift
  Mondee/View/ContentView.swift
  Mondee/View/ReceiveDataSampleView.swift
Labels: ⌚️ watchOS, 📁 Data

#85 [iOS] chore: watchOS에서 받은 데이터를 viewModel에 적용 (#84)
  Mondee/Model/TodayModel.swift
  Mondee/View/TodayView/AfterSuccessPopupView.swift
  Mondee/View/TodayView/TodayView.swift
  Mondee/ViewModel/TodayViewModel.swift
Labels: 🍎 iOS, 🛠 Chore

#72 [iOS] feat: 랜덤 먼디 캐릭터 뽑기 기능 (#70)
  Mondee.xcodeproj/project.pbxproj
  Mondee/ViewModel/MondeeDrawModel.swift
  Mondee/ViewModel/MondeeDrawTestView.swift
Labels: 🍎 iOS, ✨ Feature

#88 [iOS] feat: 캐릭터 박스에 캐릭터 표시 기능 (#50)
  Mondee.xcodeproj/project.pbxproj
  Mondee/Model/MondeeModel.swift
  Mondee/Model/PhoneDataModel.swift
  Mondee/Model/UserDataModel.swift
  Mondee/View/TodayView/AfterSuccessPopupView.swift
  Mondee/View/TodayView/MondeeBoxView.swift
  Mondee/ViewModel/MondeeDrawModel.swift
  Mondee/ViewModel/TodayViewModel.swift
Labels: 🍎 iOS, ✨ Feature

#79 [iOS] feat: 공유페이지 구현 (#52)
  Mondee.xcodeproj/project.pbxproj
  Mondee/Assets.xcassets/CollectedMondeeImg/ImgCollectedMondee002-IOS.imageset/ImgCollectedMondee002-IOS.png
  Mondee/Assets.xcassets/SharingCard/Contents.json
  Mondee/Assets.xcassets/SharingCard/SharingCard02.imageset/Contents.json
  Mondee/Assets.xcassets/SharingCard/SharingCard02.imageset/sharingCard02.png
  Mondee/Assets.xcassets/SharingCard/sharingCardBubbleButton.imageset/Contents.json
  Mondee/Assets.xcassets/SharingCard/sharingCardBubbleButton.imageset/sharingCardBubbleButton.png
  Mondee/Assets.xcassets/SharingCard/sharingCardCloudButton.imageset/Contents.json
  Mondee/Assets.xcassets/SharingCard/sharingCardCloudButton.imageset/sharingCardCloudButton.png
  Mondee/Assets.xcassets/SharingCard/sharingCardMondeeText.imageset/Contents.json
  Mondee/Assets.xcassets/SharingCard/sharingCardMondeeText.imageset/Group 320.png
  Mondee/View/CustomTabView.swift
  Mondee/View/RecordView/MonthStatistics.swift
  Mondee/View/RecordView/RecordCalendarArea.swift
  Mondee/View/RecordView/RecordCalendarView.swift
  Mondee/View/RecordView/RecordTitleArea.swift
  Mondee/View/RecordView/TotalStatistics.swift
  Mondee/View/TodayView/ShareView.swift
  Mondee/View/TodayView/SharingCardView.swift
  Mondee/View/TodayView/SharingCards/SharingCard1View.swift
  Mondee/View/TodayView/SharingCards/SharingCard2View.swift
  Mondee/View/TodayView/SharingCards/SharingCardCloudBackground.swift
  Mondee/View/TodayView/TodayView.swift
Labels: 🍎 iOS, ✨ Feature

#96 [iOS] feat: 플레이 방법 안내 구현 (#47)
  Mondee.xcodeproj/project.pbxproj
  Mondee/Assets.xcassets/GameRule/Contents.json
  Mondee/Assets.xcassets/GameRule/ImgGameRule1-iOS.imageset/Contents.json
  Mondee/Assets.xcassets/GameRule/ImgGameRule1-iOS.imageset/ImgGameRule1-iOS.png
  Mondee/Assets.xcassets/GameRule/ImgGameRule2-iOS.imageset/Contents.json
  Mondee/Assets.xcassets/GameRule/ImgGameRule2-iOS.imageset/ImgGameRule2-iOS.png
  Mondee/Assets.xcassets/GameRule/ImgGameRule3-iOS.imageset/Contents.json
  Mondee/Assets.xcassets/GameRule/ImgGameRule3-iOS.imageset/ImgGameRule3-iOS.png
  Mondee/Assets.xcassets/GameRule/ImgGameRule4-iOS.imageset/Contents.json
  Mondee/Assets.xcassets/GameRule/ImgGameRule4-iOS.imageset/ImgGameRule4-iOS.png
  Mondee/Assets.xcassets/GameRule/ImgGameRule5-iOS.imageset/Contents.json
  Mondee/Assets.xcassets/GameRule/ImgGameRule5-iOS.imageset/ImgGameRule5-iOS.png
  Mondee/View/TodayView/GameRulePopupView.swift
  Mondee/View/TodayView/TodayView.swift
Labels: 🍎 iOS, ✨ Feature

#89 [iOS] feat: 이번달, 전체 기록 표시 기능 구현 (#80)
  Mondee.xcodeproj/project.pbxproj
  Mondee/Model/UserDataModel.swift
  Mondee/View/RecordView/MonthStatistics.swift
  Mondee/View/RecordView/RecordCalendarArea.swift
  Mondee/View/RecordView/RecordCalendarView.swift
  Mondee/View/RecordView/RecordTitleArea.swift
  Mondee/View/RecordView/RecordView.swift
  Mondee/View/RecordView/TotalStatistics.swift
  Mondee/ViewModel/RecordViewModel.swift
Labels: 🍎 iOS, ✨ Feature

#95 [iOS] feat: 투데이뷰 progress bar 수정 (#94)
  Mondee/View/TodayView/MondeeLevelView.swift
Labels: 🍎 iOS, 🛠 Chore

#92 [iOS] feat: 게임 결과데이터를 멸균실에 적용 (#91)
  Mondee/Model/CleanRoomModel.swift
  Mondee/View/CleanRoomView/CleanRoomView.swift
  Mondee/View/CleanRoomView/CollectedMondeeGridView.swift
  Mondee/View/CleanRoomView/LatestCollectedMondeeView.swift
  Mondee/ViewModel/CleanViewModel.swift
Labels: 🍎 iOS, ✨ Feature

#97 [iOS] feat: 공유 페이지에 랜덤 이미지 연결 (#93)
  Mondee/View/RecordView/RecordCalendarView.swift
  Mondee/View/RecordView/RecordTitleArea.swift
  Mondee/View/TodayView/ShareView.swift
  Mondee/View/TodayView/SharingCardView.swift
  Mondee/View/TodayView/TodayView.swift
  Mondee/ViewModel/CleanViewModel.swift
  Mondee/ViewModel/RecordViewModel.swift
Labels: 🍎 iOS, ✨ Feature

#101 [iOS] fix: 타임존 해결, 게임 성공 후 앱 접속시 먼디 뽑게하기 (#100)
  Mondee/Model/PhoneDataModel.swift
  Mondee/ViewModel/TodayViewModel.swift
Labels: 🐞 Bugfix, ⌚️ watchOS, 🍎 iOS

#99 [watchOS] data: 실시간 데이터 전송 기능 구현 (#83)
  Mondee Watch App/Model/WatchLiveDataModel.swift
  Mondee Watch App/View/Play/GameOptionView.swift
  Mondee Watch App/View/Play/PlayView.swift
  Mondee Watch App/View/Result/RetryFailView.swift
  Mondee Watch App/View/Result/SuccessView.swift
  Mondee Watch App/ViewModel/GameStateManager.swift
  Mondee.xcodeproj/project.pbxproj
  Mondee/Model/PhoneLiveDataModel.swift
  Mondee/Model/UserDataModel.swift
Labels: 🍎 iOS, 📁 Data

#107 [iOS] feat: 기록뷰 네비게이션 타이틀 구현 (#106)
  Mondee/View/CleanRoomView/CleanRoomView.swift
  Mondee/View/RecordView/RecordTitleArea.swift
  Mondee/View/RecordView/RecordView.swift
Labels: 🍎 iOS, ✨ Feature

#109 [watchOS] data: 데이터 통합 전송 & 실시간 화면 전환 기능 구현 (#108)
  Mondee Watch App/Model/WatchDataModel.swift
  Mondee Watch App/Model/WatchLiveDataModel.swift
  Mondee Watch App/View/Play/GameOptionView.swift
  Mondee Watch App/View/Play/PlayView.swift
  Mondee Watch App/View/Result/RetryFailView.swift
  Mondee Watch App/View/Result/SuccessView.swift
  Mondee Watch App/ViewModel/GameStateManager.swift
  Mondee.xcodeproj/project.pbxproj
  Mondee/Model/PhoneDataModel.swift
  Mondee/Model/PhoneLiveDataModel.swift
  Mondee/Model/TodayModel.swift
  Mondee/Model/UserDataModel.swift
  Mondee/View/ContentView.swift
  Mondee/ViewModel/TodayViewModel.swift
Labels: ⌚️ watchOS, 📁 Data

#110 [iOS] design: 디테일 애니메이션 추가 (#104)
  Mondee Watch App/View/Result/FinalFailView.swift
  Mondee Watch App/View/Result/SuccessView.swift
  Mondee.xcodeproj/project.pbxproj
  Mondee/View/CleanRoomView/CleanRoomView.swift
  Mondee/View/ContentView.swift
  Mondee/View/CustomTabView.swift
  Mondee/View/RecordView/RecordTitleArea.swift
  Mondee/View/RecordView/RecordView.swift
  Mondee/View/TodayView/AfterSuccessPopupView.swift
  Mondee/View/TodayView/LevelPopupView.swift
  Mondee/View/TodayView/MondeeLevelView.swift
  Mondee/View/TodayView/TodayView.swift
Labels: 🍎 iOS, 🎨 design
